config/routes.rb
SwiftSite::Application.routes.draw do

  # http://blog.bignerdranch.com/1666-redirect-www-subdomain-to-your-apex-domain-using-the-rails-router/
  # Remove the www from the URL, e.g. don't allow that stupid subdomain.
  # Why? It causes issues with caching, namely clearing the action cache (memcache) while
  # on builtbyswift.com does NOT clear the action cache for www.builtybyswift.com. This causes
  # the two "sites" to be out of sync and nobody likes that. cstuart 2013-02-13
  # CHANGED this is disabled because we are now going to use rack rewrite to force WWW rather
  # than the bare domain. this is because heroku sounds like it does not play nicely when you
  # set up SSL to point at the bare domain (builtbyswift.com with no www)
  # constraints(host: /^www\./i) do
  #   match '(*any)' => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
  #   }
  # end

  get 'hub' => 'hub#index'
  get 'hub/expire_flickr_cache' => 'hub#expire_flickr_cache'
  get 'hub/expire_home_cache' => 'hub#expire_home_cache'


  # get '/users/my_info', to: 'users#my_info', as: 'my_info'
  # get '/users/edit_my_info', to: 'users#edit_my_info', as: 'edit_my_info'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  resources :users, only: [:index, :edit, :update, :destroy, :show] do
    collection do
      get 'campout_locations'
      get 'camper_profile'
      get 'camper_profiles'
    end
  end
  get 'profile', :to => 'users#profile'

  get 'pages/new' => 'pages#new'
  get 'pages/:path' => 'pages#show', :constraints => { :path => /[A-Za-z_-]+/ }

  resources :pages, :products, :companies, :colors, :parts, :sizes, :testimonials,
            :categories, :pre_approved_dealers, :coupons

  resources :products do
    get 'order', on: :member
  end

  resources :categories do
    get 'move', on: :member
  end

  resources :coupons do
    get 'valid', on: :member, :constraints => { :id => /[A-Za-z0-9_-]+/ }
  end

  resources :contacts do
    get 'copy', on: :collection
  end

  # # view cart
  # https://www.builtbyswift.com/cart
  #
  # # purchase what's in cart/checkout
  # https://www.builtbyswift.com/cart/checkout
  #
  # # completed purchase
  # https://www.builtbyswift.com/orders/7e59b9a5

  get 'sales/search', to: 'sales#search'

  resources :sales do
    get 'success', on: :member
    get 'ready_for_pickup', on: :member
    get 'checkout', on: :new
    post 'charge', on: :collection
    post 'coupon', on: :collection
    get 'all', on: :collection
  end

  resources :gift_certificates do
    get 'status', on: :member
  end

  get 'cart', to: 'sales#cart'
  get 'cart/checkout', to: 'sales#checkout'
  get 'orders', to: 'sales#history'
  get 'orders/:guid', to: 'sales#success', as: :order

  post 'postmaster/validate', to: 'postmaster#validate'
  post 'postmaster/rates', to: 'postmaster#rates'
  post 'postmaster/fit', to: 'postmaster#fit'
  get  'postmaster/edit_shipment', to: 'postmaster#edit_shipment'
  post 'postmaster/create_shipment', to: 'postmaster#create_shipment'
  get  'postmaster/boxes', to: 'postmaster#boxes'
  post 'postmaster/create_box', to: 'postmaster#create_box'

  get 'instagram/get_by_tag/:tag', to: 'instagram#get_by_tag'
  get 'twitter/get_by_tag/:tag', to: 'twitter#get_by_tag'
  get 'flickr/photo/:id/:label', to: 'flickr#photo'

  get 'swiftcampout', to: 'solstice#index'
  get 'solstice', to: 'solstice#index'
  get "swiftcampout/sign_in" => redirect("/users/sign_in?swiftcampout=1")
  get "swiftcampout/sign_up" => redirect("/users/sign_up?swiftcampout=1")
  get "swiftcampout/welcome", to: 'solstice#index'
  get "swiftcampout/share", to: 'solstice#share'
  get "swiftcampout/profile/:guid", to: 'solstice#profile'

  post 'wa_state_taxes/rate', to: 'wa_state_taxes#rate'

  get 'store', :to => 'homes#store'
  get "accessories" => redirect("/store")

  post 'exceptions/report', to: 'exceptions#report'

  get "experiencetheoutdoors" => redirect("http://experiencetheoutdoors.co/")

  root :to => 'homes#index'

end

app/models/company.rb
class Company < ActiveRecord::Base

  validates_presence_of :title, :email, :phone, :address, :description

  def phone_link
      num = self.phone.gsub(/[^0-9]/,'')
      "tel:+#{num}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :verify_is_admin
  layout "hub"
  cache_sweeper :application_sweeper

  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end

  private

  def company_params
    params.require(:company).permit(:title, :email, :phone, :address, :description, :delivery_time, :front_door_sign, :close_shop, :close_shop_message)
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
    <p class="hint">
        The text that google uses for the "summary" text for the site.
    </p>
  </div>
  <div class="field">
    <%= f.label :delivery_time %>
    <%= f.text_area :delivery_time %>
    <p class="hint">
        The "handmade takes time" text on the order page.
    </p>
  </div>
  <div class="field">
    <%= f.label :front_door_sign %>
    <%= f.text_area :front_door_sign %>
    <p class="hint">
      This text will appear at the top of every public page.
    </p>
  </div>
  <div class="field row">
    <label for="company_close_shop">
        <%= f.check_box :close_shop %>
        Close the shop? (this will turn off the order forms)
    </label>
  </div>
  <div class="field">
    <%= f.label :close_shop_message %>
    <%= f.text_area :close_shop_message %>
    <p class="hint">
      This text will appear instead of the order form.
    </p>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Swift Industries</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<div class="responsive-table-container">
<table class="table">
  <tr>
    <th>Title</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.title %></td>
    <td><%= company.email %></td>
    <td><%= company.phone %></td>
    <td><%= company.address %></td>
    <td><%= company.description %></td>
    <td><%= company.front_door_sign %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

<p>
  <%= link_to 'New Company', new_company_path %>
</p>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back', companies_path %>
</p>

app/views/companies/show.html.erb
<p id="notice" class="row"><%= notice %></p>

<div class="twelve columns">
    <h1>
        Swift Industries
    </h1>
</div>
<div class="four columns">
    <%= link_to raw('&larr; Hub'), hub_path, class: "btn" %>
    <%= link_to 'Edit', edit_company_path(@company), :class => "btn" %>
</div>

<div class="eight columns">
    <h4>Title</h4>
    <p>
      <%= @company.title %>
    </p>

      <h4>Email</h4>
    <p>
      <%= @company.email %>
    </p>

      <h4>Phone</h4>
    <p>
      <%= @company.phone %>
    </p>

      <h4>Address</h4>
    <p>
      <%= @company.address %>
    </p>

      <h4>Description</h4>
    <p>
      <%= @company.description %>
    </p>
</div>
<div class="eight columns">
      <h4>Delivery time</h4>
    <p>
      <%= @company.delivery_time %>
    </p>

      <h4>Front door sign</h4>
    <p>
      <% if @company.front_door_sign.present? %>
        <%= @company.front_door_sign %>
      <% else %>
        <i>blank</i>
      <% end %>
    </p>

      <h4>Is the shop closed?</h4>
    <p>
      <%= @company.close_shop %>
    </p>

      <h4>Shop closed message</h4>
    <p>
      <%= @company.close_shop_message %>
    </p>
</div>