config/routes.rb
SwiftSite::Application.routes.draw do

  # http://blog.bignerdranch.com/1666-redirect-www-subdomain-to-your-apex-domain-using-the-rails-router/
  # Remove the www from the URL, e.g. don't allow that stupid subdomain.
  # Why? It causes issues with caching, namely clearing the action cache (memcache) while
  # on builtbyswift.com does NOT clear the action cache for www.builtybyswift.com. This causes
  # the two "sites" to be out of sync and nobody likes that. cstuart 2013-02-13
  # CHANGED this is disabled because we are now going to use rack rewrite to force WWW rather
  # than the bare domain. this is because heroku sounds like it does not play nicely when you
  # set up SSL to point at the bare domain (builtbyswift.com with no www)
  # constraints(host: /^www\./i) do
  #   match '(*any)' => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
  #   }
  # end

  get 'hub' => 'hub#index'
  get 'hub/expire_flickr_cache' => 'hub#expire_flickr_cache'
  get 'hub/expire_home_cache' => 'hub#expire_home_cache'


  # get '/users/my_info', to: 'users#my_info', as: 'my_info'
  # get '/users/edit_my_info', to: 'users#edit_my_info', as: 'edit_my_info'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  resources :users, only: [:index, :edit, :update, :destroy, :show] do
    collection do
      get 'campout_locations'
      get 'camper_profile'
      get 'camper_profiles'
    end
  end
  get 'profile', :to => 'users#profile'

  get 'pages/new' => 'pages#new'
  get 'pages/:path' => 'pages#show', :constraints => { :path => /[A-Za-z_-]+/ }

  resources :pages, :products, :companies, :colors, :parts, :sizes, :testimonials,
            :categories, :pre_approved_dealers, :coupons

  resources :products do
    get 'order', on: :member
  end

  resources :categories do
    get 'move', on: :member
  end

  resources :coupons do
    get 'valid', on: :member, :constraints => { :id => /[A-Za-z0-9_-]+/ }
  end

  resources :contacts do
    get 'copy', on: :collection
  end

  # # view cart
  # https://www.builtbyswift.com/cart
  #
  # # purchase what's in cart/checkout
  # https://www.builtbyswift.com/cart/checkout
  #
  # # completed purchase
  # https://www.builtbyswift.com/orders/7e59b9a5

  get 'sales/search', to: 'sales#search'

  resources :sales do
    get 'success', on: :member
    get 'ready_for_pickup', on: :member
    get 'checkout', on: :new
    post 'charge', on: :collection
    post 'coupon', on: :collection
    get 'all', on: :collection
  end

  resources :gift_certificates do
    get 'status', on: :member
  end

  get 'cart', to: 'sales#cart'
  get 'cart/checkout', to: 'sales#checkout'
  get 'orders', to: 'sales#history'
  get 'orders/:guid', to: 'sales#success', as: :order

  post 'postmaster/validate', to: 'postmaster#validate'
  post 'postmaster/rates', to: 'postmaster#rates'
  post 'postmaster/fit', to: 'postmaster#fit'
  get  'postmaster/edit_shipment', to: 'postmaster#edit_shipment'
  post 'postmaster/create_shipment', to: 'postmaster#create_shipment'
  get  'postmaster/boxes', to: 'postmaster#boxes'
  post 'postmaster/create_box', to: 'postmaster#create_box'

  get 'instagram/get_by_tag/:tag', to: 'instagram#get_by_tag'
  get 'twitter/get_by_tag/:tag', to: 'twitter#get_by_tag'
  get 'flickr/photo/:id/:label', to: 'flickr#photo'

  get 'swiftcampout', to: 'solstice#index'
  get 'solstice', to: 'solstice#index'
  get "swiftcampout/sign_in" => redirect("/users/sign_in?swiftcampout=1")
  get "swiftcampout/sign_up" => redirect("/users/sign_up?swiftcampout=1")
  get "swiftcampout/welcome", to: 'solstice#index'
  get "swiftcampout/share", to: 'solstice#share'
  get "swiftcampout/profile/:guid", to: 'solstice#profile'

  post 'wa_state_taxes/rate', to: 'wa_state_taxes#rate'

  get 'store', :to => 'homes#store'
  get "accessories" => redirect("/store")

  post 'exceptions/report', to: 'exceptions#report'

  get "experiencetheoutdoors" => redirect("http://experiencetheoutdoors.co/")

  root :to => 'homes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

    acts_as_list
    default_scope { order('position ASC') }

    has_many :products

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :verify_is_admin
  layout "hub"
  cache_sweeper :application_sweeper

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end

  def move
    category = Category.find(params[:id])

    if params[:dir] == "up"
      category.move_higher
    end

    if params[:dir] == "down"
      category.move_lower
    end

    category.save

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p>
  <%= link_to raw('&larr; Hub'), hub_path, class: "btn" %>
  <%= link_to 'New Category', new_category_path, class: "btn" %>
</p>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td>
      <%= link_to raw("UP"), move_category_path(category, dir: "up"), class: "btn btn--table" %>
      <%= link_to raw("DOWN"), move_category_path(category, dir: "down"), class: "btn btn--table" %>
      <%= link_to 'Edit', edit_category_path(category), class: "btn btn--table" %>
      <%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete, class: "btn btn--table" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>