config/routes.rb
SwiftSite::Application.routes.draw do

  # http://blog.bignerdranch.com/1666-redirect-www-subdomain-to-your-apex-domain-using-the-rails-router/
  # Remove the www from the URL, e.g. don't allow that stupid subdomain.
  # Why? It causes issues with caching, namely clearing the action cache (memcache) while
  # on builtbyswift.com does NOT clear the action cache for www.builtybyswift.com. This causes
  # the two "sites" to be out of sync and nobody likes that. cstuart 2013-02-13
  # CHANGED this is disabled because we are now going to use rack rewrite to force WWW rather
  # than the bare domain. this is because heroku sounds like it does not play nicely when you
  # set up SSL to point at the bare domain (builtbyswift.com with no www)
  # constraints(host: /^www\./i) do
  #   match '(*any)' => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
  #   }
  # end

  get 'hub' => 'hub#index'
  get 'hub/expire_flickr_cache' => 'hub#expire_flickr_cache'
  get 'hub/expire_home_cache' => 'hub#expire_home_cache'


  # get '/users/my_info', to: 'users#my_info', as: 'my_info'
  # get '/users/edit_my_info', to: 'users#edit_my_info', as: 'edit_my_info'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  resources :users, only: [:index, :edit, :update, :destroy, :show] do
    collection do
      get 'campout_locations'
      get 'camper_profile'
      get 'camper_profiles'
    end
  end
  get 'profile', :to => 'users#profile'

  get 'pages/new' => 'pages#new'
  get 'pages/:path' => 'pages#show', :constraints => { :path => /[A-Za-z_-]+/ }

  resources :pages, :products, :companies, :colors, :parts, :sizes, :testimonials,
            :categories, :pre_approved_dealers, :coupons

  resources :products do
    get 'order', on: :member
  end

  resources :categories do
    get 'move', on: :member
  end

  resources :coupons do
    get 'valid', on: :member, :constraints => { :id => /[A-Za-z0-9_-]+/ }
  end

  resources :contacts do
    get 'copy', on: :collection
  end

  # # view cart
  # https://www.builtbyswift.com/cart
  #
  # # purchase what's in cart/checkout
  # https://www.builtbyswift.com/cart/checkout
  #
  # # completed purchase
  # https://www.builtbyswift.com/orders/7e59b9a5

  get 'sales/search', to: 'sales#search'

  resources :sales do
    get 'success', on: :member
    get 'ready_for_pickup', on: :member
    get 'checkout', on: :new
    post 'charge', on: :collection
    post 'coupon', on: :collection
    get 'all', on: :collection
  end

  resources :gift_certificates do
    get 'status', on: :member
  end

  get 'cart', to: 'sales#cart'
  get 'cart/checkout', to: 'sales#checkout'
  get 'orders', to: 'sales#history'
  get 'orders/:guid', to: 'sales#success', as: :order

  post 'postmaster/validate', to: 'postmaster#validate'
  post 'postmaster/rates', to: 'postmaster#rates'
  post 'postmaster/fit', to: 'postmaster#fit'
  get  'postmaster/edit_shipment', to: 'postmaster#edit_shipment'
  post 'postmaster/create_shipment', to: 'postmaster#create_shipment'
  get  'postmaster/boxes', to: 'postmaster#boxes'
  post 'postmaster/create_box', to: 'postmaster#create_box'

  get 'instagram/get_by_tag/:tag', to: 'instagram#get_by_tag'
  get 'twitter/get_by_tag/:tag', to: 'twitter#get_by_tag'
  get 'flickr/photo/:id/:label', to: 'flickr#photo'

  get 'swiftcampout', to: 'solstice#index'
  get 'solstice', to: 'solstice#index'
  get "swiftcampout/sign_in" => redirect("/users/sign_in?swiftcampout=1")
  get "swiftcampout/sign_up" => redirect("/users/sign_up?swiftcampout=1")
  get "swiftcampout/welcome", to: 'solstice#index'
  get "swiftcampout/share", to: 'solstice#share'
  get "swiftcampout/profile/:guid", to: 'solstice#profile'

  post 'wa_state_taxes/rate', to: 'wa_state_taxes#rate'

  get 'store', :to => 'homes#store'
  get "accessories" => redirect("/store")

  post 'exceptions/report', to: 'exceptions#report'

  get "experiencetheoutdoors" => redirect("http://experiencetheoutdoors.co/")

  root :to => 'homes#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  include PgSearch

  has_many :shipments
  has_many :gift_certificates

  before_validation :populate_status, :populate_guid, on: :create

  # validates_presence_of :email, :description
  # validates :email, format: /@/

  STATUSES = ["Not Shipped", "Printed", "Shipped", "Deleted"]
  attr_reader :STATUSES
  validates :status, :inclusion => { :in => STATUSES, :message => "%{value} is not a valid status" }

  validates_presence_of :email, :amount, :total, :guid, :status

  scope :not_shipped, -> { where(status: 'Not Shipped').order("created_at DESC") }
  scope :printed,     -> { where(status: 'Printed').order("created_at DESC").limit(120) }
  scope :shipped,     -> { where(status: 'Shipped').order("created_at DESC").limit(60) }
  scope :deleted,     -> { where(status: 'Deleted').order("created_at DESC").limit(60) }

  pg_search_scope :search, against: [
    :email, :guid, :city, :state, :zip_code, :country, :stripe_id, :phone_no,
    :contact, :company, :gift_certificate_guid, :shipping_contact, :coupon_code,
    :line1
  ]

  # This needs to exclude instances where the product hasn't
  # shipped, and instances where it shipped, but was not shipped
  # with Postmaster
  # def self.get_all_shipping_price_diff
  #   total_actual   = Shipment.sum(:cost)
  #   total_expected = Sale.sum(:shipping_charge)
  #
  #   if (total_expected > total_actual)
  #     diff = total_expected - total_actual
  #     perc = ((diff.to_f / total_expected.to_f) * 100).to_s.split(".")[0]
  #
  #     return ['+', diff, perc]
  #   else
  #     diff = total_actual - total_expected
  #     perc = ((diff.to_f / total_expected.to_f) * 100).to_s.split(".")[0]
  #
  #     return ['-', diff, perc]
  #   end
  # end

  def get_shipping_price_diff
    # expected is what we charged the customer
    # actual is what we paid to ship

    if self.shipping_charge && self.shipments.present?
      expected = self.shipping_charge.to_i

      shipping_costs = self.shipments.map do |shipment|
        shipment.cost.to_i
      end
      actual = shipping_costs.inject{|sum,x| sum + x }

      # matched
      if expected == actual
        return ["", "0", "0"]
      # expected costs were greater than actual
      elsif expected > actual
        diff = expected - actual
        diff_percent = get_diff_percent diff, expected

        return ["+", diff, diff_percent]
      # expected costs were less than actual
      else
        diff = actual - expected
        diff_percent = get_diff_percent diff, expected

        return ["-", diff, diff_percent]
      end
    else
      ""
    end
  end

  private

  def get_diff_percent diff, expected
    ((diff.to_f / expected.to_f) * 100).to_s.split('.')[0]
  end

  def populate_guid
    if self.guid.present?
      raise "Cannot set guid on sale. It's already set."
    else
      self.guid = SecureRandom.hex(4)
    end
  end

  def populate_status
    if self.status.present?
      raise "Cannot set status on sale. It's already set."
    else
      self.status = "Not Shipped"
    end
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_filter :verify_is_admin, :except => [ :checkout, :create, :success, :cart, :charge, :history, :coupon ]

  cache_sweeper :application_sweeper

  # GET /sales
  # GET /sales.json
  def index
    @sales_not_shipped = Sale.not_shipped
    @sales_printed     = Sale.printed
    @sales_shipped     = Sale.shipped
    @sales_deleted     = Sale.deleted

    render :layout => "hub"
    #
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @sales }
    # end
  end

  def all
    @sales = Sale.order("created_at DESC").page params[:page]

    render layout: "hub"
  end

  # GET /sales
  # GET /sales.json
  def cart
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])
    @shipments = @sale.shipments

    if @sale.gift_certificate_guid.present?
      logger.debug "=> Trying to get GC"

      begin
        @gift_certificate = GiftCertificate.find_by_guid! @sale.gift_certificate_guid
        logger.debug "=> Got GC"
      rescue Exception => e
        ExceptionNotifier.notify_exception(
          e,
          :env => request.env,
          :data => {:message => "Getting GC failed"}
        )
        logger.warn e
      end
    end

    if @sale.coupon_code.present?
      begin
        @coupon = Coupon.find_by_code! @sale.coupon_code
      rescue Exception => e
        ExceptionNotifier.notify_exception(
          e,
          :env => request.env,
          :data => {:message => "Getting Coupon failed"}
        )
        logger.warn e
      end
    end

    render :layout => "hub"
  end

  # GET /sales/1234/success
  # GET /sales/1234/success.json
  def success
    @sale = Sale.find_by_guid(params[:guid])
    render_404 if @sale.nil?

    @shipments = @sale.shipments

    # This is bad if this happens
    if @sale.description.present?
      @description = JSON.parse(@sale.description)
    else
      @description = nil
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  def ready_for_pickup
    @sale = Sale.find params[:id]
    @sale.update_attributes({ status: "Shipped" })
    SalesMailer.ready_for_pickup(@sale).deliver_now
    redirect_to(@sale, notice: 'Email successfully sent to customer.')
  end

  def checkout
    respond_to do |format|
      format.html # new.html.erb
      # format.json { render json: @sale }
    end
  end

  def history
    if user_signed_in?
      @sales = Sale.where(email: current_user.email)
    else
      @sales = []
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  def search
    @results = Sale.search params[:q]
    render layout: "hub"
  end

  # POST /sales/charge.json
  def charge
    begin
      # Create the charge
      stripe_charge = Stripe::Charge.create(
        amount:      params[:total].to_i,
        currency:    "usd",
        card:        params[:stripeToken],
        description: "#{params[:email]}"
      )

      render json: { id: stripe_charge.id }.to_json
    rescue Stripe::CardError => e
      # The card has been declined or
      # some other error has occured
      logger.error e.inspect

      # FIXME appears to not actually be responding with JSON. :(
      render json: { error: e }.to_json, status: :internal_server_error
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    # Create the sale
    @sale = Sale.new(
      contact:           params[:contact],
      company:           params[:company],
      email:             params[:email],
      description:       params[:description],
      amount:            params[:amount],
      total:             params[:total],
      tax_rate:          params[:tax_rate],
      tax_amount:        params[:tax_amount],
      line1:             params[:line1],
      # line2:             params[:line2],
      city:              params[:city],
      state:             params[:state],
      zip_code:          params[:zip_code],
      country:           params[:country],
      phone_no:          params[:phone_no],
      commercial:        params[:commercial] || false,
      weight:            params[:weight],
      pickup:            params[:pickup] || false,
      shipping_contact:  params[:shipping_contact],
      shipping_provider: params[:shipping_provider],
      shipping_charge:   params[:shipping_charge],
      shipping_service:  params[:shipping_service],
      shipping_service_is_flat_rate:  params[:shipping_service_is_flat_rate],
      stripe_id:         params[:stripe_id],
      gift_certificate_guid: params[:gift_certificate_guid],
      gift_cert_remain:      params[:gift_cert_remain],
      gift_cert_available:   params[:gift_cert_available],
      gift_cert_applied:     params[:gift_cert_applied],
      total_with_gift_cert:  params[:total_with_gift_cert],
      coupon_code:           params[:coupon_code] || nil,
      saved_with_coupon:     params[:saved_with_coupon] || false
    )

    if @sale.save
      # Send an email
      # TODO run this in the background or whatever
      # TODO don't want to fail order if this fails
      # but it'd be nice to know if it's happening
      begin
        create_gift_certificates @sale
      rescue Exception => e
        throw_exception e
      end

      begin
        update_gift_certificates @sale
      rescue Exception => e
        throw_exception e
      end

      begin
        update_inventory @sale
      rescue Exception => e
        throw_exception e
      end

      begin
        # Create the contact if they sign up for spam
        if params[:send_me_marketing_emails]
          Contact.create(email: params[:email])
        end
      rescue Exception => e
        throw_exception e
      end

      SalesMailer.success(params[:email], @sale.guid).deliver_now
      SalesMailer.notify_swift(@sale).deliver_now

      render json: { guid: @sale.guid }.to_json
    else
      render json: { error: @sale.errors }, :status => :unprocessable_entity
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    if params[:sale][:status] == "Shipped" && params[:sale][:email] == "true"
      SalesMailer.shipped_flat_rate(@sale).deliver_now
    end

    respond_to do |format|
      if @sale.update_attributes(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  protected

  def create_gift_certificates sale
    description = JSON.parse(sale.description)

    description["products"].each do |product|
      if product["kind"] == "Gift Certificate"
        price_in_cents = product["price"].to_i * 100
        gift_certificate = GiftCertificate.new(sale_id: sale.id, amount: price_in_cents)

        if gift_certificate.save
          logger.info "Created Gift Certificate"
          GiftCertificatesMailer.notify_swift(gift_certificate).deliver_now
        else
          ExceptionNotifier.notify_exception(
            e,
            env: request.env,
            data: { message: "Failed to create Gift Certificate" }
          )
        end

      else
        logger.info "SalesController#create_gift_certificates: Product is not a gift certificate. #{product["kind"]}"
      end
    end
  end

  def update_gift_certificates sale
    if sale.gift_certificate_guid.present?
      gift = GiftCertificate.find_by_guid sale.gift_certificate_guid

      begin
        # logger.info "Updating Gift Certificate #{sale.gift_certificate_guid}. Subtracting #{sale.gift_cert_applied} from #{gift.remaining_amount}."
        gift.remaining_amount = gift.remaining_amount - sale.gift_cert_applied
        gift.save!
      rescue Exception => e
        ExceptionNotifier.notify_exception(
          e,
          env: request.env,
          data: { message: "Failed to update Gift Certificate" }
        )
      end
    else
      logger.info "SalesController#update_gift_certificates: Sale has no gift certificate"
    end
  end

  def update_inventory sale
    description = JSON.parse sale[:description]
    sold_products = description["products"]

    sold_products.each do |sold_product|
      if sold_product["selectedSize"].present?
        size = Size.find sold_product["selectedSize"]["id"]
      end

      product = Product.find sold_product["id"]
      product.update_inventory(sold_product["quantity"], size) unless product.nil?
    end
  end

  def throw_exception e
    logger.error e

    ExceptionNotifier.notify_exception(
      e,
      env: request.env,
      data: { message: "Post sale task failed." }
    )
  end

  def sale_params
    params.require(:sale).permit(:description, :email, :amount, :weight, :line1, :line2, :city, :state, :zip_code, :country, :shipping_provider, :shipping_service, :shipping_charge, :stripe_id, :tax_rate, :tax_amount, :total, :pickup, :status, :phone_no, :contact, :company, :commercial, :postmaster_id, :shipping_tracking_number, :gift_certificate_guid, :gift_cert_remain, :gift_cert_applied, :total_with_gift_cert, :shipping_contact, :shipping_service_is_flat_rate, :coupon_code, :saved_with_coupon)
  end
end

app/helpers/sales_helper.rb
module SalesHelper

    def last_name sale
        return "n/a" if sale.contact.nil?

        if sale.contact.include? " "
            sale.contact.split(" ").last
        else
            sale.contact
        end
    end

end

app/views/sales/_sales_table.html.erb
<div class="responsive-table-container">
<table class="table">
  <thead>
  <tr>
    <th>Order Date</th>
    <th>Customer URL</th>
    <th>Hub URL</th>
    <th>Email</th>
    <th>Last Name</th>
    <th>Amount</th>
    <th>Pickup?</th>
    <th>Flat Rate?</th>
    <th>Boxes</th>
    <th>Tracking URL(s)</th>
    <th>Shipping $ +/-</th>
    <th></th>
    <th style="display:none"></th>
    <th style="display:none"></th>
  </tr>
  </thead>
  <tbody>

<% sales.each do |sale| %>
  <tr>
    <td>
      <nobr><%= sale.created_at.strftime("%b %-d") %></nobr>
    </td>
    <td>
      <a href="/orders/<%= sale.guid %>">
        /orders/<%= sale.guid %>
      </a>
    </td>
    <td><%= link_to "/sales/#{sale.id}", sale %></td>
    <td>
      <%= mail_to sale.email, truncate(sale.email, length: 20), subject: "Your Swift Industries Order [#{sale.guid}]", body: "Hi #{sale.contact}, \n\nThanks,\nSwift Industries\n\nhttps://www.builtbyswift.com/orders/#{sale.guid}" %>
    </td>
    <td>
      <nobr>
        <%= image_tag "flags/#{sale.country.downcase}.png" %> <%= last_name(sale) %>
      </nobr>
    </td>
    <td><%= number_to_currency(cents_to_dollars(sale.total)) %></td>
    <td>
      <% if sale.pickup? %>
        <span style="color:green; font-size: 120%;">
          ✓
        </span>
      <% else %>
        <span style="color:red; font-size: 120%;">
          ✗
        </span>
      <% end %>
    </td>
    <td>
      <% if sale.shipping_service_is_flat_rate? %>
        <span style="color:green; font-size: 120%;">
          ✓
        </span>
      <% else %>
        <span style="color:red; font-size: 120%;">
          ✗
        </span>
      <% end %>
    </td>
    <td>
      <% if sale.shipments.present? %>
        <%= sale.shipments.length %>
      <% end %>
    </td>
    <td>
      <% if sale.shipments.present? %>
        <% sale.shipments.each do |shipment| %>
          <%= render 'tracking_link', carrier: shipment.carrier, num: shipment.tracking_number %>
        <% end %>
      <% end %>
    </td>
    <td>
      <% if sale.shipments.present? %>
        <nobr>
          <% if sale.get_shipping_price_diff[0] == "+" %>
            <span class="ship-diff">
              <span class="ship-diff__arr">&uarr;</span>
          <% else %>
            <span class="ship-diff" style="color: red;">
              <span class="ship-diff__arr">&darr;</span>
          <% end %>
          <%= number_to_currency(cents_to_dollars(sale.get_shipping_price_diff[1])) %>
          <span class="ship-diff__perc">(<%= sale.get_shipping_price_diff[2] %>%)</span>
          </span>
        </nobr>
      <% end %>
    </td>
    <td style="display:none"><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td style="display:none"><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/sales/_show_shipping.html.erb
<%# Pickup sale and it's been printed %>
<% if @sale.pickup? && @sale.status == "Printed" %>
  <div class="grid">
    <div class="unit">
      Customer will pick up their order.
    </div>
  </div>
  <div class="grid">
    <div class="unit half">
      <strong>Send "ready for pickup" email to customer and move to shipped.</strong>
      <br><br>
      <%= link_to 'Moved to Shipped + Email', { controller: "sales", action: "ready_for_pickup", id: @sale }, class: 'btn' %>
    </div>
    <div class="unit half">
      Or, move the sale to shipped with no email.
      <br><br>
      <%= link_to "Move to Shipped", sale_path(id: @sale.id, sale: { status: "Shipped" }), :remote => true, :method => :put, "data-type" => :json, id: 'markAsShipped', class: 'btn' %>
    </div>
  </div>
<%# Pickup sale and it's been shipped %>
<% elsif @sale.pickup? && @sale.status == "Shipped" %>
  <p>
      Order is ready for pickup.
  </p>
<%# Not a pickup %>
<% else %>
  <%# Not shipped yet %>
  <% if @shipments.blank? %>
    <%# Sale is shipped, but has no shipments. Manual move. %>
    <% if @sale.status == "Shipped" %>
      <p>
        This sale was manually moved to shipped. You can undo and change the status back to "Printed".
      </p>
      <p>
        <%= link_to "Undo", sale_path(id: @sale.id, sale: { status: "Printed" }), :remote => true, :method => :put, "data-type" => :json, id: 'undoMarkAsShipped', class: 'btn' %>
      </p>
    <%# Sale not shipped. %>
    <% else %>
      <% if @sale.shipping_service_is_flat_rate? %>
        Customer was charged <%= number_to_currency(cents_to_dollars(@sale.shipping_charge)) %> via flat rate shipping.
      <% end %>
      <h4>
        Ship Sale via Postmaster
      </h4>
      <p>
        <%= link_to 'Ship it', { controller: "postmaster", action: "edit_shipment", id: @sale }, class: 'btn' %>
      </p>
      <h4>
        Or, Move Sale to "Shipped" Manually
      </h4>
      <p>
        <%= link_to "Mark as 'Shipped' with email to customer", sale_path(id: @sale.id, sale: { status: "Shipped", email: true }), :remote => true, :method => :put, "data-type" => :json, id: 'markAsShipped', class: 'btn' %>
      </p>
      <p>
        <%= link_to "Mark as 'Shipped' without email", sale_path(id: @sale.id, sale: { status: "Shipped", email: false }), :remote => true, :method => :put, "data-type" => :json, id: 'markAsShippedNoEmail', class: 'btn' %>
      </p>
    <% end %>
  <%# Sale is shipped. Can add more shipments to sale. %>
  <% else %>
    <p>
      <span class="hey--yay">
        This order has been shipped.
      </span>
    </p>
    <% @shipments.each_with_index do |shipment, index| %>
      <% if index > 0 %>
        <hr>
      <% end %>
      <p>
        <b>Postmaster ID:</b>
        <%= shipment.postmaster_id %>
      </p>
      <p>
        <b>Tracking Number:</b>
        <%= render 'tracking_link', carrier: shipment.carrier, num: shipment.tracking_number %>
      </p>
      <p>
        <b>Weight:</b>
        <%= shipment.weight %>lbs.
      </p>
      <% if shipment.envelope.present? %>
        <p>
          <b>Envelope:</b>
          <%= shipment.envelope %>
        </p>
      <% else %>
        <p>
          <b>Dimensions (W &#215; H &#215; L):</b>
          <%= shipment.width %> &#215; <%= shipment.height %> &#215; <%= shipment.length %>
        </p>
      <% end %>
      <p>View details (including the shipping label):<br>
        <a href="https://www.postmaster.io/dashboard/shipments/id/<%= shipment.postmaster_id %>">
          https://www.postmaster.io/dashboard/shipments/id/<%= shipment.postmaster_id %></a>.
      </p>
      <P>
        <b>Cost:</b>
        <%= number_to_currency(cents_to_dollars(shipment.cost)) %>
    <% end %>
    <p>
      <%= link_to 'Ship another box', { controller: "postmaster", action: "edit_shipment", id: @sale }, class: 'btn' %>
    </p>
  <% end %>
<% end %>

app/views/sales/_show_stripe_link.html.erb
<% if Rails.env == "production" %>
  <a href="https://dashboard.stripe.com/prod/payments/<%= @sale.stripe_id %>" class="btn">
    View on Stripe
  </a>
<% else %>
  <a href="https://dashboard.stripe.com/test/payments/<%= @sale.stripe_id %>" class="btn">
    View on Stripe
  </a>
<% end %>

app/views/sales/all.html.erb
<%= content_for :css do %>
  <style>
    .container {
      width: auto;
      padding: 10px;
    }
    .page.current {
      background-color: #ffa;
    }
  </style>
<% end %>

<h1>
  All Sales
</h1>
<p>
  <%= link_to raw('&larr; Hub'), hub_path, class: "btn" %>
  <%= link_to raw('&larr; Sales'), sales_path, class: "btn" %>
</p>
<% cache @sales do %>
  <%= paginate @sales %>
  <%= render 'sales_table', sales: @sales, title: 'All' %>
  <%= paginate @sales %>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Sales</h1>
<p>
  The first 60 sales for each tab are shown. To view older sales <%= link_to "view all", all_sales_path %>.
</p>
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <p>
      <%= link_to raw('&larr; Hub'), hub_path, class: "btn" %>
    </p>
  </div>
  <div class="col-xs-12 col-sm-6">
    <%= render 'search' %>
  </div>
</div>
<div class="tabs">
  <div class="tab">
    New <span class="demph"><%= @sales_not_shipped.length %></span>
  </div>
  <div class="tab">
    Printed <span class="demph"><%= @sales_printed.length %></span>
  </div>
  <div class="tab">
    Shipped <span class="demph"><%= @sales_shipped.length %></span>
  </div>
  <div class="tab">
    Trash <span class="demph"><%= @sales_deleted.length %></span>
  </div>
  <div class="tab">
    <a href="all">
      All
    </a>
  </div>
  <div class="tab-divider"></div>
  <div class="card">
    <% cache @sales_not_shipped do %>
      <%= render 'sales_table', sales: @sales_not_shipped, title: 'Not Shipped' %>
    <% end %>
  </div>
  <div class="card">
    <% cache @sales_printed do %>
      <%= render 'sales_table', sales: @sales_printed, title: 'Printed' %>
    <% end %>
  </div>
  <div class="card">
    <% cache @sales_shipped do %>
      <%= render 'sales_table', sales: @sales_shipped, title: 'Shipped' %>
    <% end %>
  </div>
  <div class="card">
    <% cache @sales_deleted do %>
      <%= render 'sales_table', sales: @sales_deleted, title: 'Deleted' %>
    <% end %>
  </div>
  <div class="card">
    <p>
      <%= link_to "View all", all_sales_path, class: "btn" %>
  </div>
</div>

<%= content_for :js do %>
<script>
    $('h3')
        .css('cursor', 'pointer')
        .on('click', function() {
            $(this).next('table').toggle()
        })
</script>
<script>
  $(document).ready(function(){
    $('.tabs').tabs();
  });
</script>
<% end %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/search.html.erb
<h1>
  Search results for <b><%= params[:q] %></b>
</h1>
<%= render 'search' %>
<%= render 'sales_table', sales: @results, title: 'Results' %>